server:
  servlet:
    context-path:
  port:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto:

tracto:
  download-schedule:
    url:
    auth-header:
    session-url:
  time-update-schedule:
  time-update-session:
