server:
  servlet:
    context-path: /api/
  port: 8080

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto:

tracto:
  download-schedule:
    url:
    auth-header:
  time-update-schedule:
